# Generated by Django 5.2.1 on 2025-08-17 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subdepartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('leader', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'Subdepartement',
                'verbose_name_plural': 'Subdepartements',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(default='Atas Meja', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='received_by',
            field=models.CharField(blank=True, max_length=62, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='requested_by',
            field=models.CharField(blank=True, max_length=62, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wms.item'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='subdepartement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.subdepartement'),
        ),
    ]
