# Generated by Django 5.2.1 on 2025-08-17 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0002_subdepartement_item_location_transaction_received_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='subdepartement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.subdepartement'),
        ),
    ]
